### ISSUE TITLE
How to change port of container?

### ISSUE THREAD

**Issue by hshar7** [zuazo/dradis-docker#1]
Hello,
I am trying to change the port of the container. Any idea?
It seems like no matter what I do it remains at 3000!

**Comment by zuazo** [comment]
See [`run_example.sh`](https://github.com/zuazo/dradis-docker/blob/master/run_example.sh):

```bash
docker run \
  -p 3000:3000 \
  --volume "$(pwd)/dbdata:/dbdata" \
zuazo/dradis "${@}"
```

You can change you host port with the `-p` option there. For example:

```bash
docker run \
  -p 4000:3000 \
  --volume "$(pwd)/dbdata:/dbdata" \
zuazo/dradis "${@}"
```

**Comment by hshar7** [comment]
Seems to still be running on 3000

**Comment by hshar7** [comment]
Seems like there was a problem with my iptables on centos vm. Fixed thanks to comment on https://github.com/docker/docker/issues/1871
Thanks @zuazo
